#NORUN no

diff --git a/.github/workflows/GithubWorkflow.yaml b/.github/workflows/GithubWorkflow.yaml
--- a/.github/workflows/GithubWorkflow.yaml
+++ b/.github/workflows/GithubWorkflow.yaml
@@ -10,9 +10,9 @@ jobs:
     - name: Check Commit Message
       id: check_message
       run: |
-        if [[ $(git log -1 --pretty=%B) == '#NORUN'* ]]; then
-          echo "Commit message starts with #NORUN. Cancelling the workflow."
-          exit 1
+        if [[ "${{ github.event.head_commit.message }}" == "#NORUN"* ]]; then
+          echo "Commit message starts with #NORUN, skipping the workflow."
+          exit 78 # Use a non-zero exit code to indicate skipping the workflow
         fi
       continue-on-error: true
 
