#NORUN

diff --git a/.github/workflows/GithubWorkflow.yaml b/.github/workflows/GithubWorkflow.yaml
--- a/.github/workflows/GithubWorkflow.yaml
+++ b/.github/workflows/GithubWorkflow.yaml
@@ -12,7 +12,7 @@ jobs:
       run: |
         if [[ "${{ github.event.head_commit.message }}" == "#NORUN" ]]; then
           echo "Commit message starts with #NORUN, cancelling the workflow."
-          exit 78 # Use a non-zero exit code to indicate cancelling the workflow
+          exit 1 # Use a non-zero exit code to indicate cancelling the workflow
         fi
       continue-on-error: true
 
